language: objective-c
xcode_workspace: Carthage.xcworkspace
xcode_scheme: carthage
osx_image: xcode7.1
before_install: true
install: true
git:
  submodules: false
script: BUILD_TOOL=xctool script/cibuild
notifications:
  email: false
  slack:
    secure: lblNhCx6581hiPskQQnH663QY/HHqs6y8rMCLIff1Ryq0ngBaTwBJZ6E5tAR8oWTGWg3nMAAm/AaJPQGFC9jnKxtpWJhuEF58RY+EBe1Rz3gjKmacvEZS+PW+k3cRrRPZr6Vh6D8d0cb1gfM7BvGZar21ipBC/WcnNden3LxZ+0=
env:
  global:
    secure: DofNs+Ej7JblkkGMTHOl4XMBfv0EKVvzZU7OOm7U6Hyxu0J0SN6E3s61Q4HUWOBvM3Yrxf+8jpFKI29w69WArmRPpmK6GCaZar8ldUBHNmN3gaeOaGmGyrmnre4hxHjJzc0E3HAmJ03v94HW5JwQzKpIUjxg4dSttJMT6WOmnxE=
    secure: "ehB+3qjRcHR9tCeX9omi69V7XihSdySXVo45GoyqLncCa90tpeLviI+m2XRJn2ajHtrz+iwBaBut6buFpcbCrSOdHsZ5FQb2sGkGprll/Tz8B2XvNRqpQan2eFouO2/SPpOVDurpbqf78KsRSRD6mMNuCS4AfKM/hDnbGUxzCfs="
before_deploy:
  - brew install hub
deploy:
  - provider: releases
    api-key:
      secure: c1fMI4p8oUVGi7SkDLqXpZDhrVVnLWU8J6+rWc3pTMmeNmEGopZpCiiQupHoHXx+Fq3+8R4M2iG0IgfcVTb6q5HD2RH0+q57/p9vcYIlCS8E/1o2BPUHUfH1Poc1vs7VdFpjWFmbm6Twnnffbz3AsELjv3mJyRxR6fUAliwfnWk=
    file:
      - Carthage.pkg
      - CarthageKit.framework.zip
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: script/brew-publish
    on:
      branch: brew-publish
